name: Create languages analysis

on:
  push:
    branches: [ master ]
    paths-ignore:
      - '**.md'
      - '**.png'
      - '**.jpg'
      - '**.csv'
#   schedule:
#     - cron: '0 15 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests pyyaml matplotlib

    - name: Create language analysis image
      env:
        TOKEN: ${{ secrets.LANGUAGE_STATISTICS_TOKEN }}
      run: |
        python3 -m analysis --job LanguageStatisticsJob --github-api-token "${TOKEN}"
